import modulo_aritmetica,modulo_potencias
print("Ingresa un numero:")
num1=input()
num1=float(num1)
print("Ingresa otro numero:")
num2=input()
num2=float(num2)
print("La suma de ",num1,"+ ",num2," Es ",modulo_aritmetica.sumar(num1,num2))
print("La resta de ",num1,"- ",num2," Es ",modulo_aritmetica.restar(num1,num2))
print("La multiplicacion de ",num1,"* ",num2," Es ",modulo_aritmetica.multiplicar(num1,num2))
print("La division de ",num1,"/ ",num2," Es ",modulo_aritmetica.dividir(num1,num2))
print("El resto de ",num1,"% ",num2," Es ",modulo_aritmetica.resto(num1,num2))
print("El cuadrado de ",num1," Es ",modulo_potencias.cuadrado(num1))
print("El cubo de ",num2," Es ",modulo_potencias.cubo(num2))
